
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


server.port=8083

grpc.client.customer.host=localhost
grpc.client.customer.port=9081

grpc.client.inventory.host=localhost
grpc.client.inventory.port=9082


spring.application.name=quote-service