# Puerto para Spring Boot (REST / Actuator / etc)
server.port=8083

# Puerto para tu servidor gRPC de Autenticacion
grpc.server.port=9093

# Nombre de la aplicacion en Spring
spring.application.name=auth-service

# Llave secreta
jwt.secret=hola_soy_una_llave_secreta_increiblemente_larga_y_segura_para_que_no_nos_hacken_gracias_ITSON