
package presentacion.vistas;

import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * Archivo: PanelEncabezado.java
 * 
 * @author Ariel Eduardo Borbón Izaguirre - 253080
 * @author Sebastián Bórquez Huerta - 253080
 * @author Chris Fitch Lopez - 252379
 * @author Yuri Germán García López - 253080
 * @author Manuel Romo López - 253080
 * 
 */
public class PanelEncabezado extends javax.swing.JPanel {

    /**
     * Creates new form PanelEncabezado
     */
    public PanelEncabezado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 30));
        setMaximumSize(new java.awt.Dimension(1000, 89));
        setMinimumSize(new java.awt.Dimension(1000, 89));
        setPreferredSize(new java.awt.Dimension(1000, 89));
        setLayout(new java.awt.BorderLayout());

        ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource("/logo.png"));
        java.awt.Image imgEscalada = iconoOriginal.getImage().getScaledInstance(100, 57, java.awt.Image.SCALE_SMOOTH);
        jLabel1.setIcon(new javax.swing.ImageIcon(imgEscalada));
        jLabel1.setToolTipText("");
        jLabel1.setFocusable(false);
        Dimension tamañoFijo = new Dimension(100, 57);

        jLabel1.setPreferredSize(tamañoFijo);
        jLabel1.setMaximumSize(tamañoFijo);
        jLabel1.setMinimumSize(tamañoFijo);
        jLabel1.setSize(tamañoFijo);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SGISCA");
        add(jLabel2, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
