
package presentacion.vistas;

import dtos.vehicle.VehicleSummaryDTO; 
import dtos.customer.CustomerSummaryDTO;
import java.awt.Dimension;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import presentacion.interfaces.IControlAgregarCotizacion;
import presentacion.interfaces.vistas.IVistaSeleccionClienteAuto;

/**
 *
 * Archivo: VistaSeleccionClienteAuto.java
 * 
 * @author Ariel Eduardo Borbón Izaguirre - 253080
 * @author Sebastián Bórquez Huerta - 253080
 * @author Chris Fitch Lopez - 252379
 * @author Yuri Germán García López - 253080
 * @author Manuel Romo López - 253080
 * 
 */
public class VistaSeleccionClienteAuto extends JFrame implements IVistaSeleccionClienteAuto{

    private static final Logger LOG = Logger.getLogger(VistaSeleccionClienteAuto.class.getName());
    
    private IControlAgregarCotizacion control;
    
    /**
     * Creates new form VistaSeleccionClienteAuto
     */
    public VistaSeleccionClienteAuto(IControlAgregarCotizacion control) {
        initComponents();
        this.control = control;
        btnContinuar.setEnabled(false);
        
        setLocationRelativeTo(null);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imgCliente = new javax.swing.JLabel();
        imgAutomovil = new javax.swing.JLabel();
        Añadir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmbBoxClientes = new javax.swing.JComboBox<>();
        cmbBoxAutomoviles = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanel2Layout.rowHeights = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nuevo Servicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(36, 63, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panelPrincipal.add(jPanel2, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 61, 0, 32);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Automóvil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 20);
        jPanel1.add(jLabel3, gridBagConstraints);

        ImageIcon iconoOriginalCliente = new javax.swing.ImageIcon(getClass().getResource("/cliente.png"));
        java.awt.Image imgEscaladaCliente = iconoOriginalCliente.getImage().getScaledInstance(100, 80, java.awt.Image.SCALE_SMOOTH);
        imgCliente.setIcon(new javax.swing.ImageIcon(imgEscaladaCliente));
        imgCliente.setMaximumSize(new java.awt.Dimension(100, 80));
        imgCliente.setMinimumSize(new java.awt.Dimension(100, 80));
        imgCliente.setPreferredSize(new java.awt.Dimension(100, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        jPanel1.add(imgCliente, gridBagConstraints);

        ImageIcon iconoOriginalAutomovil = new javax.swing.ImageIcon(getClass().getResource("/automovil.png"));
        java.awt.Image imgEscaladaAutomovil = iconoOriginalAutomovil.getImage().getScaledInstance(100, 57, java.awt.Image.SCALE_SMOOTH);
        imgAutomovil.setIcon(new javax.swing.ImageIcon(imgEscaladaAutomovil));
        imgAutomovil.setMaximumSize(new java.awt.Dimension(100, 80));
        imgAutomovil.setMinimumSize(new java.awt.Dimension(100, 80));
        imgAutomovil.setPreferredSize(new java.awt.Dimension(100, 80));
        Dimension dimensionAutomovil = new Dimension(100, 80);
        imgAutomovil.setPreferredSize(dimensionAutomovil);
        imgAutomovil.setMaximumSize(dimensionAutomovil);
        imgAutomovil.setMinimumSize(dimensionAutomovil);
        imgAutomovil.setSize(dimensionAutomovil);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        jPanel1.add(imgAutomovil, gridBagConstraints);

        Añadir.setBackground(new java.awt.Color(211, 233, 255));
        Añadir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(Añadir, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(204, 229, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Añadir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jButton1, gridBagConstraints);

        cmbBoxClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxClientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 11);
        jPanel1.add(cmbBoxClientes, gridBagConstraints);

        cmbBoxAutomoviles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBoxAutomoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxAutomovilesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 39);
        jPanel1.add(cmbBoxAutomoviles, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(jPanel1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        jPanel3.setLayout(new java.awt.BorderLayout());

        btnContinuar.setBackground(new java.awt.Color(204, 255, 204));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel3.add(btnContinuar, java.awt.BorderLayout.LINE_END);

        btnVolver.setBackground(new java.awt.Color(255, 255, 204));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel3.add(btnVolver, java.awt.BorderLayout.LINE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(jPanel3, gridBagConstraints);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        regresarSeleccionClienteAutomovil();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        continuar();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void cmbBoxAutomovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxAutomovilesActionPerformed
        seleccionarAutomovil();
    }//GEN-LAST:event_cmbBoxAutomovilesActionPerformed

    private void cmbBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxClientesActionPerformed
        seleccionarCliente();
    }//GEN-LAST:event_cmbBoxClientesActionPerformed

    private void seleccionarCliente(){
        CustomerSummaryDTO clienteSeleccionado = (CustomerSummaryDTO) cmbBoxClientes.getSelectedItem();
        
        if(clienteSeleccionado != null){
            Long idClienteSeleccionado = clienteSeleccionado.getId();
            control.seleccionarCliente(idClienteSeleccionado);    
        }    
    }
    
    private void regresarSeleccionClienteAutomovil(){
        
        control.atrasPrincipal();
        
    }
    
    private void seleccionarAutomovil(){
        VehicleSummaryDTO automovilSeleccionado = (VehicleSummaryDTO) cmbBoxAutomoviles.getSelectedItem();
        
        if(automovilSeleccionado != null){
            control.seleccionarAutomovil(automovilSeleccionado);
            btnContinuar.setEnabled(true);
        } else{
            btnContinuar.setEnabled(false);
        }
        
    }
    
    private void continuar(){
        
        control.seleccionarClienteAutomovil();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<VehicleSummaryDTO> cmbBoxAutomoviles;
    private javax.swing.JComboBox<CustomerSummaryDTO> cmbBoxClientes;
    private javax.swing.JLabel imgAutomovil;
    private javax.swing.JLabel imgCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarClientes(List<CustomerSummaryDTO> clientes) {
        cmbBoxClientes.removeAllItems();
        clientes.forEach(cmbBoxClientes::addItem);
    }

    @Override
    public void cargarAutosCliente(List<VehicleSummaryDTO> automoviles) {
        cmbBoxAutomoviles.removeAllItems();
        automoviles.forEach(cmbBoxAutomoviles::addItem);
    }
    
    public void cargarClientes(List<CustomerSummaryDTO> clientes, Long idClienteSeleccionado) {
        cmbBoxClientes.removeAllItems();
        clientes.forEach(cmbBoxClientes::addItem);
        
        if (idClienteSeleccionado != null) {
        clientes.stream()
            .filter(c -> c.getId().equals(idClienteSeleccionado))
            .findFirst()
            .ifPresent(cmbBoxClientes::setSelectedItem);
        }
        
    }


    public void cargarAutosCliente(List<VehicleSummaryDTO> automoviles, Long idAutomovilSeleccionado) {
        
        cmbBoxAutomoviles.removeAllItems();
        automoviles.forEach(cmbBoxAutomoviles::addItem);
        
        if (idAutomovilSeleccionado != null) {
        automoviles.stream()
            .filter(a -> a.getId().equals(idAutomovilSeleccionado))
            .findFirst()
            .ifPresent(cmbBoxClientes::setSelectedItem);
        }
    }
    
    @Override
    public void mostrarMensaje(String mensajeError) {
        JOptionPane.showMessageDialog(this, mensajeError, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void mostrar() {
        setVisible(true);
    }

    @Override
    public void ocultar() {
        dispose();
    }


}
