
package presentacion.vistas;

import dtos.automovil.AutomovilResumenDTO;
import dtos.servicio.ServicioResumenDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import presentacion.interfaces.IControlAgregarCotizacion;
import presentacion.interfaces.vistas.IVistaServicios;

/**
 *
 * Archivo: VistaServicios.java
 * 
 * @author Ariel Eduardo Borbón Izaguirre - 253080
 * @author Sebastián Bórquez Huerta - 253080
 * @author Yuri Germán García López - 253080
 * @author Manuel Romo López - 253080
 * 
 */
public class VistaServicios extends JFrame implements IVistaServicios{

    private IControlAgregarCotizacion control;
    
    private JPanel panelActivo;
    private ServicioResumenDTO servicioSeleccionado;
    
    private final Border BORDE_PANEL_SERVICIO = BorderFactory.createLineBorder(Color.LIGHT_GRAY, 2, true);
    private final Border BORDE_PANEL_SERVICIO_SELECCIONADO = BorderFactory.createLineBorder(new Color(0, 120, 150), 2);
    
    private final Color COLOR_PANEL_SERVICIO_HOVER = new Color(245, 245, 245);
    private final Color COLOR_PANEL_SERVICIO_SELECCIONADO = new Color(220, 240, 230);
    
    private final Border MARGEN_INTERNO_PANEL_SERVICIO = BorderFactory.createEmptyBorder(10, 10, 10, 10);

    /**
     * Creates new form IVistaServicios
     */
    public VistaServicios(IControlAgregarCotizacion control) {
        initComponents();
        this.control = control;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelEncabezado1 = new presentacion.vistas.PanelEncabezado();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmpTxtNombreServicioBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelServicios = new javax.swing.JPanel();
        scrollServicios = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        getContentPane().add(panelEncabezado1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Servicios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        cmpTxtNombreServicioBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmpTxtNombreServicioBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpTxtNombreServicioBuscarActionPerformed(evt);
            }
        });
        cmpTxtNombreServicioBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmpTxtNombreServicioBuscarKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel2.add(cmpTxtNombreServicioBuscar, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Buscar: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        panelServicios.setBackground(new java.awt.Color(102, 255, 204));
        panelServicios.setLayout(new java.awt.GridBagLayout());

        scrollServicios.setBackground(new java.awt.Color(242, 242, 242));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelServicios.add(scrollServicios, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(panelServicios, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, java.awt.BorderLayout.LINE_START);

        btnContinuar.setBackground(new java.awt.Color(204, 255, 204));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel4.add(btnContinuar, java.awt.BorderLayout.LINE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        
        seleccionarServicio();
        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void cmpTxtNombreServicioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpTxtNombreServicioBuscarActionPerformed

        buscarServicio();
        
    }//GEN-LAST:event_cmpTxtNombreServicioBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        atras();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmpTxtNombreServicioBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmpTxtNombreServicioBuscarKeyReleased
        buscarServicio();
    }//GEN-LAST:event_cmpTxtNombreServicioBuscarKeyReleased

    private void atras(){
        control.atrasSeleccionarServicio();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JTextField cmpTxtNombreServicioBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private presentacion.vistas.PanelEncabezado panelEncabezado1;
    private javax.swing.JPanel panelServicios;
    private javax.swing.JScrollPane scrollServicios;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarServicios(List<ServicioResumenDTO> servicios) {
        
        JPanel panelContenedor = new JPanel();
        panelContenedor.setLayout(new GridBagLayout());
        panelContenedor.setOpaque(false);
        GridBagConstraints gbc = new GridBagConstraints();


        if (servicios == null || servicios.isEmpty()) {

            JLabel lblSinResultados = new JLabel("No se encontraron servicios.");
            lblSinResultados.setFont(new Font("Segoe UI", java.awt.Font.BOLD, 18));
            lblSinResultados.setForeground(Color.GRAY);
            
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            gbc.anchor = GridBagConstraints.CENTER;
            
            panelContenedor.add(lblSinResultados, gbc);
            
        } else {

            int margenServicio = 15;
            gbc.insets = new Insets(margenServicio, margenServicio, margenServicio, margenServicio);
            gbc.anchor = GridBagConstraints.NORTHWEST;

            int anchoDisponible = scrollServicios.getWidth() > 0 ? scrollServicios.getWidth() : 800;
        
            int columnasMaximas = 5;
            int columnaActual = 0;
            int filaActual = 0;

            int anchoServicio = (anchoDisponible - ((columnasMaximas + 1) * margenServicio)) / columnasMaximas - 20;
            
            for(ServicioResumenDTO servicio : servicios) {

                JPanel panelServicio = new JPanel(new BorderLayout(0, 10));
                panelServicio.setBackground(Color.WHITE);
                panelServicio.setBorder(BorderFactory.createCompoundBorder(BORDE_PANEL_SERVICIO, MARGEN_INTERNO_PANEL_SERVICIO));
                
                panelServicio.setPreferredSize(new Dimension(anchoServicio, anchoServicio));
                panelServicio.setMinimumSize(new Dimension(anchoServicio, anchoServicio));
               
                panelServicio.setCursor(new Cursor(java.awt.Cursor.HAND_CURSOR));
                
                configurarListenerPanelServicio(panelServicio, servicio);

                String nombreServicio = "<html><div style='text-align: center; width: " + (anchoServicio - 50) + "px; font-size: 9px;'>" 
                               + servicio.getNombre() 
                               + "</div></html>";
                JLabel labelNombre = new JLabel(nombreServicio, SwingConstants.CENTER);
                panelServicio.add(labelNombre, BorderLayout.SOUTH);

                int tamañoIcono = (int)(anchoServicio * 0.6);
                ImageIcon iconoRedimensionado = redimensionarIcono(servicio.getDireccionIcono(), tamañoIcono, tamañoIcono);

                if (iconoRedimensionado != null) {
                    JLabel labelIcono = new JLabel(iconoRedimensionado);
                    labelIcono.setHorizontalAlignment(SwingConstants.CENTER);
                    panelServicio.add(labelIcono, BorderLayout.CENTER);
                }

                gbc.gridx = columnaActual;
                gbc.gridy = filaActual;

                panelContenedor.add(panelServicio, gbc);

                columnaActual++;
                if (columnaActual >= columnasMaximas) {
                    columnaActual = 0;
                    filaActual++;
                }
            }
        }

        scrollServicios.setOpaque(false);
        scrollServicios.setViewportView(panelContenedor);
        
        // 3. Limpiar variables de selección por seguridad al recargar
        btnContinuar.setEnabled(false);
        panelActivo = null;
        servicioSeleccionado = null;
    }
    
    private void configurarListenerPanelServicio(JPanel panelServicio, ServicioResumenDTO servicio){
        panelServicio.addMouseListener(new MouseAdapter() {
    
            @Override
            public void mouseClicked(MouseEvent e) {

                if (panelActivo != null) {
                    panelActivo.setBackground(Color.WHITE);
                    panelActivo.setBorder(BorderFactory.createCompoundBorder(BORDE_PANEL_SERVICIO, MARGEN_INTERNO_PANEL_SERVICIO));
                }

                panelServicio.setBackground(COLOR_PANEL_SERVICIO_SELECCIONADO); 
                panelServicio.setBorder(BorderFactory.createCompoundBorder(BORDE_PANEL_SERVICIO_SELECCIONADO, MARGEN_INTERNO_PANEL_SERVICIO));

                panelActivo = panelServicio;
                servicioSeleccionado = servicio;

                btnContinuar.setEnabled(true);
            }

            @Override
            public void mouseEntered(MouseEvent e) {

                if (panelServicio != panelActivo) {
                    panelServicio.setBackground(COLOR_PANEL_SERVICIO_HOVER);
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {

                if (panelServicio != panelActivo) {
                    panelServicio.setBackground(Color.WHITE);
                }
            }
        });
    }
    
    private ImageIcon redimensionarIcono(String direccionImagen, int ancho, int alto) {
        URL imgURL = getClass().getResource("/" + direccionImagen);

        if (imgURL != null) {
            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(imgURL);
            java.awt.Image imgEscalada = iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);
            return new javax.swing.ImageIcon(imgEscalada);
        } else {
            System.err.println("No se encontró la imagen en la ruta: /" + direccionImagen);
            return null;
        }
    }
    
    private void seleccionarServicio(){
        if(servicioSeleccionado != null){
            
            control.seleccionarServicio(servicioSeleccionado);
            
        }
    }
    
    private void buscarServicio(){
        
        String nombreServicio = cmpTxtNombreServicioBuscar.getText();
        control.buscarServicio(nombreServicio);
        
    }
    
    

    @Override
    public void mostrar() {
        setVisible(true);
    }

    @Override
    public void ocultar() {
        dispose();
    }

    @Override
    public void mostrarMensaje(String mensajeError) {
        JOptionPane.showMessageDialog(this, mensajeError, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

 
}
